imports:
    - { resource: view.yml }

parameters:
    support_tools.command.dump_info.class: EzSystems\EzSupportToolsBundle\Command\SystemInfoDumpCommand
    support_tools.system_info.collector_registry.class: EzSystems\EzSupportToolsBundle\SystemInfo\Registry\IdentifierBased
    support_tools.system_info.output_registry.class: EzSystems\EzSupportToolsBundle\SystemInfo\OutputFormatRegistry
    support_tools.system_info.ezc.wrapper.class: EzSystems\EzSupportToolsBundle\SystemInfo\EzcSystemInfoWrapper
    support_tools.system_info.collector.composer.lock_file.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\JsonComposerLockSystemInfoCollector
    support_tools.system_info.collector.database.doctrine.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\DoctrineDatabaseSystemInfoCollector
    support_tools.system_info.collector.system.ez.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzSystemInfoCollector
    support_tools.system_info.collector.hardware.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.system_info.collector.php.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcPhpSystemInfoCollector
    support_tools.system_info.collector.symfony.kernel.config.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\ConfigurationSymfonyKernelSystemInfoCollector
    support_tools.system_info.output_format.json.class: EzSystems\EzSupportToolsBundle\SystemInfo\OutputFormat\JsonOutputFormat
    support_tools.ez_url_list:
        contact: "https://ez.no/About-eZ/Contact-Us"
        license: "https://ez.no/About-our-Software/Licenses-and-agreements"
        ttl: "https://ez.no/About-our-Software/Licenses-and-agreements/eZ-Trial-and-Test-License-Agreement-eZ-TTL-v2.1"
        service_life: "https://support.ez.no/Public/Service-Life"
        support_service: "https://ez.no/Services/Support-Maintenance"
        training_service: "https://ez.no/Services/Training"
        consulting_service: "https://ez.no/Services/Consulting"
        ee_product: "https://ez.no/Products/eZ-Platform-Enterprise-Edition"
        install_ee: "https://doc.ezplatform.com/en/{ez.release}/getting_started/install_ez_enterprise/"
        doc: "https://doc.ezplatform.com"
        update: "https://doc.ezplatform.com/en/latest/releases/updating_ez_platform/"
        gpl_faq: "https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLModuleLicense"
        support: "https://support.ez.no"

services:
    support_tools.command.dump_info:
        class: "%support_tools.command.dump_info.class%"
        arguments:
            - "@support_tools.system_info.collector_registry"
            - "@support_tools.system_info.output_registry"
        tags:
            - { name: console.command }

    support_tools.system_info.collector_registry:
        class: "%support_tools.system_info.collector_registry.class%"

    support_tools.system_info.output_registry:
        class: "%support_tools.system_info.output_registry.class%"

    support_tools.system_info.ezc.wrapper:
        class: "%support_tools.system_info.ezc.wrapper.class%"
        lazy: true

    # SystemInfoCollectors

    support_tools.system_info.collector.system.ez:
        class: "%support_tools.system_info.collector.system.ez.class%"
        arguments:
            - "@support_tools.system_info.collector.composer.lock_file"
            - "%kernel.debug%"
        # Can't tag this before v0.3 (2.5?) as it will blow up in admin UI for missing templates there
        # And it does not look like there is any way to add it from this package, so maybe it needs to be made extensible(?)
        #tags: [{ name: "support_tools.system_info.collector", identifier: "ez" }]

    support_tools.system_info.collector.composer.lock_file:
        class: "%support_tools.system_info.collector.composer.lock_file.class%"
        arguments:
            - "%kernel.project_dir%/composer.lock"
            - "%kernel.project_dir%/composer.json"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "composer" }

    support_tools.system_info.collector.database.doctrine:
        class: "%support_tools.system_info.collector.database.doctrine.class%"
        arguments:
            - "@ezpublish.persistence.connection"
        lazy: true
        tags:
            - { name: "support_tools.system_info.collector", identifier: "database" }

    support_tools.system_info.collector.hardware.ezc:
        class: "%support_tools.system_info.collector.hardware.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "hardware" }

    support_tools.system_info.collector.php.ezc:
        class: "%support_tools.system_info.collector.php.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "php" }

    support_tools.system_info.collector.symfony.kernel.config:
        class: "%support_tools.system_info.collector.symfony.kernel.config.class%"
        arguments:
            - "@kernel"
            - "%kernel.bundles%"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "symfony_kernel" }

    # SystemInfoOutputFormats

    support_tools.system_info.output_format.json:
        class: "%support_tools.system_info.output_format.json.class%"
        tags:
            - { name: "support_tools.system_info.output_format", format: "json" }
