services:
    support_tools.view.system_info_view_builder:
        class: EzSystems\EzSupportToolsBundle\View\SystemInfoViewBuilder
        arguments:
            - "@ezpublish.view.configurator"
            - "@support_tools.system_info.collector_registry"

    EzSystems\EzSupportToolsBundle\Controller\SystemInfoController:
        tags:
            - { name: controller.service_arguments }

    support_tools.view.controller:
        alias: EzSystems\EzSupportToolsBundle\Controller\SystemInfoController
        public: true

    support_tools.view.system_info.provider:
        class: "%ezpublish.view_provider.configured.class%"
        arguments: ["@support_tools.view.matcher_factory"]
        tags:
            - {name: ezpublish.view_provider, type: 'EzSystems\EzSupportToolsBundle\View\SystemInfoView', priority: 10}

    support_tools.view.matcher_factory:
        class: "%ezpublish.view.matcher_factory.class%"
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'EzSystems\EzSupportToolsBundle\View\Matcher'

    support_tools.view.matcher_factory.dynamically_configured:
        class: eZ\Publish\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: support_tools.view.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@support_tools.view.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ezpublish.config.resolver'
            $parameterName: system_info_view
