language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    # re-enable when / if coverage is disabled for faster test runs
    #- phpenv config-rm xdebug.ini
    - travis_retry composer selfupdate
    # Avoid memory issues on composer install
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer install --prefer-dist --no-interaction

script: php bin/phpunit --coverage-text

notifications:
    email: false
