language: php

php:
    - 5.5
    - 5.6
    - 7.0

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - composer selfupdate
    - composer install --prefer-dist

script: phpunit --coverage-text

notifications:
    email: false
