dist: xenial
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: CHECK_CS=true

# test only on matching branches (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - travis_retry composer selfupdate
    # Avoid memory issues on composer install
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # Install packages
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit
    - if [ "$CHECK_CS" = "true" ]; then vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false
