imports:
    - { resource: service_aliases.yaml }
    - { resource: view.yaml }
    - { resource: systeminfo.yaml }
    - { resource: events.yaml }

parameters:
    support_tools.command.dump_info.class: EzSystems\EzSupportToolsBundle\Command\SystemInfoDumpCommand
    support_tools.system_info.collector_registry.class: EzSystems\EzSupportToolsBundle\SystemInfo\Registry\IdentifierBased
    support_tools.system_info.output_registry.class: EzSystems\EzSupportToolsBundle\SystemInfo\OutputFormatRegistry
    support_tools.system_info.ezc.wrapper.class: EzSystems\EzSupportToolsBundle\SystemInfo\EzcSystemInfoWrapper
    support_tools.system_info.collector.composer.lock_file.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\JsonComposerLockSystemInfoCollector
    support_tools.system_info.collector.system.ibexa.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\IbexaSystemInfoCollector
    support_tools.system_info.collector.hardware.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.system_info.collector.php.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcPhpSystemInfoCollector
    support_tools.system_info.collector.symfony.kernel.config.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\ConfigurationSymfonyKernelSystemInfoCollector
    support_tools.system_info.output_format.json.class: EzSystems\EzSupportToolsBundle\SystemInfo\OutputFormat\JsonOutputFormat
    ezplatform_support_tools.system_info.powered_by.name: ''
    ibexa.system_info.ibexa_url_list:
        contact: "https://www.ibexa.co/about-ibexa/contact-us"
        license: "https://www.ibexa.co/software-information/licenses-and-agreements"
        ttl: "https://www.ibexa.co/software-information/licenses-and-agreements/ez-trial-and-test-license-agreement-ez-ttl-v2.1"
        service_life: "https://support.ibexa.co/Public/Service-Life"
        support_service: "https://www.ibexa.co/services/support-maintenance"
        training_service: "https://www.ibexa.co/services/training"
        consulting_service: "https://www.ibexa.co/services/consulting-services"
        ee_product: "https://www.ibexa.co/products"
        install_ee: "https://doc.ibexa.co/en/{ez.release}/getting_started/install_ez_enterprise/"
        doc: "https://doc.ibexa.co"
        update: "https://doc.ibexa.co/en/latest/updating/updating_ez_platform/"
        gpl_faq: "https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLModuleLicense"
        support: "https://support.ibexa.co"
    support_tools.ez_url_list: '%ibexa.system_info.ibexa_url_list%' # BC

services:
    # EventSubscriber
    EzSystems\EzSupportToolsBundle\EventSubscriber\AddXPoweredByHeader:
        arguments: ["%ezplatform_support_tools.system_info.powered_by.name%"]
        tags:
            - { name: kernel.event_subscriber }

    # Console
    support_tools.command.dump_info:
        class: "%support_tools.command.dump_info.class%"
        arguments:
            - "@support_tools.system_info.collector_registry"
            - "@support_tools.system_info.output_registry"
        tags:
            - { name: console.command }

    support_tools.system_info.collector_registry:
        class: "%support_tools.system_info.collector_registry.class%"

    support_tools.system_info.output_registry:
        class: "%support_tools.system_info.output_registry.class%"

    support_tools.system_info.ezc.wrapper:
        class: "%support_tools.system_info.ezc.wrapper.class%"
        lazy: true

    # SystemInfoCollectors
    support_tools.system_info.collector.system.ibexa:
        class: "%support_tools.system_info.collector.system.ibexa.class%"
        arguments:
            - "@support_tools.system_info.collector.composer.lock_file"
            - "%kernel.debug%"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "ibexa" }

    support_tools.system_info.collector.composer.lock_file:
        class: "%support_tools.system_info.collector.composer.lock_file.class%"
        arguments:
            - "%kernel.project_dir%/composer.lock"
            - "%kernel.project_dir%/composer.json"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "composer" }

    EzSystems\EzSupportToolsBundle\SystemInfo\Collector\RepositorySystemInfoCollector:
        lazy: true
        autowire: true
        arguments:
            $db: '@ezpublish.persistence.connection'
        tags:
            - { name: "support_tools.system_info.collector", identifier: "repository" }

    support_tools.system_info.collector.hardware.ezc:
        class: "%support_tools.system_info.collector.hardware.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "hardware" }

    support_tools.system_info.collector.php.ezc:
        class: "%support_tools.system_info.collector.php.ezc.class%"
        arguments:
            - "@support_tools.system_info.ezc.wrapper"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "php" }

    support_tools.system_info.collector.symfony.kernel.config:
        class: "%support_tools.system_info.collector.symfony.kernel.config.class%"
        arguments:
            - "@kernel"
            - "%kernel.bundles%"
        tags:
            - { name: "support_tools.system_info.collector", identifier: "symfony_kernel" }

    # SystemInfoOutputFormats
    support_tools.system_info.output_format.json:
        class: "%support_tools.system_info.output_format.json.class%"
        tags:
            - { name: "support_tools.system_info.output_format", format: "json" }

    # Gateways
    EzSystems\EzSupportTools\Storage\MetricsProvider:
        alias: EzSystems\EzSupportTools\Storage\AggregateMetricsProvider

    EzSystems\EzSupportTools\Storage\AggregateMetricsProvider:
        arguments:
            $metrics: !tagged_locator { tag: ibexa.system_info.metrics, index_by: identifier }

    EzSystems\EzSupportTools\Storage\Metrics\RepositoryConnectionAwareMetrics:
        abstract: true
        arguments:
            $connection: '@ezpublish.persistence.connection'

    EzSystems\EzSupportTools\Storage\Metrics\PublishedContentObjectsCountMetrics:
        autowire: true
        tags:
            - { name: ibexa.system_info.metrics, identifier: published }

    EzSystems\EzSupportTools\Storage\Metrics\UsersCountMetrics:
        autowire: true
        tags:
            - { name: ibexa.system_info.metrics, identifier: users }

    EzSystems\EzSupportTools\Storage\Metrics\DraftsCountMetrics:
        autowire: true
        tags:
            - { name: ibexa.system_info.metrics, identifier: drafts }

    EzSystems\EzSupportTools\Storage\Metrics\VersionsCountMetrics:
        autowire: true
        tags:
            - { name: ibexa.system_info.metrics, identifier: versions }

    EzSystems\EzSupportTools\Storage\Metrics\ContentTypesCountMetrics:
        autowire: true
        tags:
            - { name: ibexa.system_info.metrics, identifier: content_types }
