name: CI

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request: ~

env:
  COMPOSER_ROOT_VERSION: 1.0.x-dev
jobs:
  tests:
    name: Tests
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
        composer_options: [ "" ]
        experimental: [false]
        include:
          - php: '8.0'
            composer_options: "--ignore-platform-req php"
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: redis
          tools: cs2pr

      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-progress --no-suggest ${{ matrix.composer_options }}"

      - name: Run test suite
        run: composer run-script --timeout=600 test

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run code style check
        run: composer run-script check-cs -- --format=checkstyle | cs2pr